import Head from 'next/head';
import Image from 'next/image';
import Carousel from '../components/Carousel';
import Destinations from '../components/Destinations';
import Hero from '../components/Hero';
import Navbar from '../components/Navbar';
import Search from '../components/Search';
import Selects from '../components/Selects';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<Navbar />
				<Hero />
				<Destinations />
				<Search />
				<Selects />
				<Carousel />
			</div>
		</div>
	);
}
